<?php
/**
 * @copyright Copyright © 2021 Avarda. All rights reserved.
 * @package   Avarda_Checkout
 */
/** @var $block \Avarda\Checkout\Block\Checkout */
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script src="<?= $block->getCheckOutClientScriptPath(); ?>.js"></script>
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        var options = {
            divId: "avarda-checkout-iframe",
            purchaseId: "<?= $block->getPurchaseId(); ?>",
            done: function (purchaseId) {
                window.location.href = "<?= $block->getSaveOrderUrl(); ?>purchase/" + purchaseId;
            },
            purchaseCompletedCallbackUrl: '<?= $block->getCompleteCallbackUrl() ?>',
            callbackUrlBase: '<?= $block->getCallbackUrl() ?>purchase/',
            callbackUrl: '<?= $block->getCallbackUrl() ?>purchase/',
            redirectUrl: "<?= $block->getBaseUrl() ?>"
        };
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
            return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
        })
    </script>
</div>
